repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        entry: bash -c 'isort "$@"; git add -u' --
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        entry: bash -c 'black "$@"; git add -u' --
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-coding==1.3.2",
            "flake8-copyright==0.2.4",
            "flake8-debugger==4.1.2",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
      - id: check-json
      - id: requirements-txt-fixer
      - id: check-vcs-permalinks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude_types: [json]
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.12
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML==5.4.0
          - types-requests==0.1.11
          - types-tabulate==0.8.3
  - repo: meta
    hooks:
      - id: check-useless-excludes
default_language_version:
  python: python3
